# Generated by Django 4.1.4 on 2023-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benzin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('turi', models.CharField(max_length=120)),
                ('manzili', models.CharField(max_length=120)),
                ('narx', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Gaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('turi', models.CharField(max_length=120)),
                ('manzili', models.CharField(max_length=120)),
                ('narx', models.CharField(max_length=120)),
            ],
        ),
    ]
